import { ApiProperty, ApiPropertyOptional, PickType, OmitType, IntersectionType } from '@nestjs/swagger'
import { IsNotEmpty, IsNumber, Min, IsOptional } from 'class-validator'
import { Type, Transform } from 'class-transformer'
import { UserInterface } from '@/module/user/user.interface'
import { toArrayNumber } from '@/utils/validate'
